export { default as Form } from './Form.vue'
export { default as SocialMedia } from './SocialMedia.vue'
export { default as MainInformation } from './MainInformation.vue'
export { default as Logo } from './Logo.vue'
export { default as Banner } from './Banner.vue'
export { default as Footer } from './Footer.vue'
